// Map base values to ISO country codes
export const baseToCountryCode: Record<string, string> = {
  fr_fr: "FR",
  com_en: "US",
  co_uk_fr: "GB",
  ca_en: "CA",
  ca_fr: "CA",
  de_de: "DE",
  es_es: "ES",
  it_it: "IT",
  ch_fr: "CH",
  ch_de: "CH",
  be_fr: "BE",
  be_nl: "BE",
  com_mx_s: "MX",
  com_br_pt: "BR",
  com_ar_s: "AR",
  com_tr_tr: "TR",
  co_ma_fr: "MA",
  se_sv: "SE",
  com_au_fr: "AU",
  co_il_iw: "IL",
  pl_pl: "PL",
  cl_e: "CL",
  nl_nl: "NL",
  lu_de: "LU",
  lu_fr: "LU",
  sn_fr: "SN",
  cm_en: "CM",
  co_jp_ja: "JP",
  ru_ru: "RU",
  co_za_fr: "ZA",
  at_de: "AT",
  com_co_es: "CO",
  gr_el: "GR",
  co_nz_fr: "NZ",
  co_in_fr: "IN",
  com_hk_zh: "HK",
  ie_fr: "IE",
  com_sg_fr: "SG",
  cz_cs: "CZ",
  sk_sk: "SK",
  lt_lt: "LT",
  pt_pt: "PT",
  com_my_ms: "MY",
  dk_da: "DK",
  co_kr_ko: "KR",
  fi_fi: "FI",
  ge_ka: "GE",
  co_id_id: "ID",
  no_no: "NO",
  ro_ro: "RO",
};

export function getCountryNameForBase(base: string): string {
  const countryCode = baseToCountryCode[base];
  if (!countryCode) {
    return base;
  }

  // Simple mapping for common countries
  const countryNames: Record<string, string> = {
    FR: "France",
    US: "United States",
    GB: "United Kingdom",
    CA: "Canada",
    DE: "Germany",
    ES: "Spain",
    IT: "Italy",
    CH: "Switzerland",
    BE: "Belgium",
    MX: "Mexico",
    BR: "Brazil",
    AR: "Argentina",
    TR: "Turkey",
    MA: "Morocco",
    SE: "Sweden",
    AU: "Australia",
    IL: "Israel",
    PL: "Poland",
    CL: "Chile",
    NL: "Netherlands",
    LU: "Luxembourg",
    SN: "Senegal",
    CM: "Cameroon",
    JP: "Japan",
    RU: "Russia",
    ZA: "South Africa",
    AT: "Austria",
    CO: "Colombia",
    GR: "Greece",
    NZ: "New Zealand",
    IN: "India",
    HK: "Hong Kong",
    IE: "Ireland",
    SG: "Singapore",
    CZ: "Czech Republic",
    SK: "Slovakia",
    LT: "Lithuania",
    PT: "Portugal",
    MY: "Malaysia",
    DK: "Denmark",
    KR: "South Korea",
    FI: "Finland",
    GE: "Georgia",
    ID: "Indonesia",
    NO: "Norway",
    RO: "Romania",
  };

  return countryNames[countryCode] || base;
}
